//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bhaptics.SDK2
{
    using System;
    using UnityEngine;
    
    
    public class BhapticsEvent
    {
        
        public const string R_LITTLE = "r_little";
        
        public const string R_INDEX = "r_index";
        
        public const string R_MIDDLE = "r_middle";
        
        public const string L_LITTLE = "l_little";
        
        public const string R_RING = "r_ring";
        
        public const string L_RING = "l_ring";
        
        public const string L_INDEX = "l_index";
        
        public const string L_MIDDLE = "l_middle";
    }
}
